/**
 * Yearly snapshot on rollover.
 *
 * Fires when `/ecole/config` is updated AND `lastArchivedAnnee`
 * either appears for the first time or changes to a new value.
 * That field is written by the rollover flow (`executeFinalArchive`
 * in `src/lib/rollover.ts`) when the admin clicks "Archiver l'année"
 * and the full archive pass succeeds.
 *
 * When the trigger fires, we kick off a Firestore export to
 * `gs://<project>-backups/yearly/<annee>/` — kept forever (no GCS
 * lifecycle rule covers this path). This is the canonical
 * end-of-year snapshot for dispute resolution and long-term archival.
 *
 * Two triggers cover the yearly case:
 *
 *   1. This function — fires at the natural moment, immediately
 *      after admin finalizes the year. Captures the data in its
 *      final clean state (all archives written, live collections
 *      reset).
 *
 *   2. `yearlySnapshotFallback` — scheduled for August 31 at 03:00.
 *      Checks if `lastArchivedAnnee` matches the school year that
 *      just ended. If NOT (admin forgot to run rollover), triggers
 *      an emergency snapshot anyway and emails the admin a nudge.
 *
 * Together these ensure no school year goes un-snapshotted regardless
 * of admin diligence.
 *
 * Idempotency: the output path `yearly/<annee>/` is per-année. If
 * this function fires twice for the same année (e.g. admin runs
 * rollover, hits an error, re-runs), the second export will land at
 * a sub-path generated by the Firestore export API and the earlier
 * snapshot is preserved. Both snapshots are kept — slight cost
 * duplication, no data risk.
 */

import { onDocumentUpdated } from 'firebase-functions/v2/firestore'
import { logger } from 'firebase-functions/v2'
import { v1 } from '@google-cloud/firestore'

const exportClient = new v1.FirestoreAdminClient()

interface EcoleConfigDoc {
  anneeActive?: string
  lastArchivedAnnee?: string
}

export const yearlySnapshotOnRollover = onDocumentUpdated(
  {
    document: 'ecole/config',
    region: 'us-central1',
    timeoutSeconds: 540,
  },
  async (event) => {
    const before = event.data?.before?.data() as EcoleConfigDoc | undefined
    const after = event.data?.after?.data() as EcoleConfigDoc | undefined
    if (!after) return

    // Fire only when lastArchivedAnnee changed to a non-empty value
    const wasBefore = before?.lastArchivedAnnee ?? null
    const nowAfter = after.lastArchivedAnnee ?? null

    if (!nowAfter) {
      // Field absent or cleared — not an archive event
      return
    }
    if (wasBefore === nowAfter) {
      // Unrelated config update (e.g. school changed ville or telephone)
      return
    }

    const annee = nowAfter
    const projectId = process.env.GCLOUD_PROJECT ?? ''
    if (!projectId) {
      logger.error('yearlySnapshotOnRollover: GCLOUD_PROJECT not set')
      throw new Error('GCLOUD_PROJECT environment variable missing')
    }

    const bucket = process.env.BACKUP_BUCKET ?? `${projectId}-backups`
    // Use the année as the path segment. "2025-2026" is safe in a URL.
    const outputUriPrefix = `gs://${bucket}/yearly/${annee}`
    const dbName = exportClient.databasePath(projectId, '(default)')

    logger.info('yearlySnapshotOnRollover: starting export', {
      annee,
      outputUriPrefix,
    })

    try {
      const [response] = await exportClient.exportDocuments({
        name: dbName,
        outputUriPrefix,
        collectionIds: [],
      })
      logger.info('yearlySnapshotOnRollover: export initiated', {
        operationName: response.name,
        annee,
      })
    } catch (err) {
      logger.error('yearlySnapshotOnRollover: export failed', {
        error: (err as Error).message,
        annee,
      })
      throw err
    }
  }
)
